// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4k8kpWY7B-EuGRqnj55McEBVSFoz2Ua0',
    appId: '1:25916358077:web:19a0d5b28fe566443026d4',
    messagingSenderId: '25916358077',
    projectId: 'yolog2',
    authDomain: 'yolog2.firebaseapp.com',
    storageBucket: 'yolog2.firebasestorage.app',
    measurementId: 'G-WZTFWNRY1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGIU1lglXhv23aciTqIW6Z4Eu35cz4drM',
    appId: '1:25916358077:android:3e56f09a5a9461b23026d4',
    messagingSenderId: '25916358077',
    projectId: 'yolog2',
    storageBucket: 'yolog2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmNDtJzdzToB0jTEq-g67OZAPaTMjvDqo',
    appId: '1:25916358077:ios:02cbed7bfbde28123026d4',
    messagingSenderId: '25916358077',
    projectId: 'yolog2',
    storageBucket: 'yolog2.firebasestorage.app',
    iosBundleId: 'com.example.yolog2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmNDtJzdzToB0jTEq-g67OZAPaTMjvDqo',
    appId: '1:25916358077:ios:02cbed7bfbde28123026d4',
    messagingSenderId: '25916358077',
    projectId: 'yolog2',
    storageBucket: 'yolog2.firebasestorage.app',
    iosBundleId: 'com.example.yolog2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4k8kpWY7B-EuGRqnj55McEBVSFoz2Ua0',
    appId: '1:25916358077:web:2a2108132c0040223026d4',
    messagingSenderId: '25916358077',
    projectId: 'yolog2',
    authDomain: 'yolog2.firebaseapp.com',
    storageBucket: 'yolog2.firebasestorage.app',
    measurementId: 'G-0N5VGSPT36',
  );
}
